### ISSUE TITLE
Channel scan not adding any pids -> no channel found

### ISSUE THREAD

**Issue by Jalle19** [oe-alliance/satip-client#23]
I've tried to get this plugin working twice now, and I always hit the same wall.

I configure vtuner.conf like this:

```
0=desc:minisatip,ipaddr:10.110.5.11,tuner_type:DVB-S,uuid:11223344-9999-0000-b7ae-0022b7f0056e,vtuner_type:satip_client,tcpdata:1
```

Then I start a manual scan using a mux I know works. The URL in minisatip looks like this:

```
http://10.110.5.11:8080/?fe=0&src=2&freq=11509&pol=V&msys=DVBS2&mtype=8psk&sr=23000&pids=
```

Notice that `pids=` is empty, which means minisatip doesn't do anything and nothing is returned in the stream -> no channels found.

How can I make channel scanning work? tvheadend seems to magically add `pids=0,1,16,17,256,259,260,262` when I scan the same mux.

@catalinii do you know if this is a minisatip bug or a bug in this client? :thinking: I've googled for hours and read the source code but I still have no idea where the problem is.

**Comment by Jalle19** [comment]
This seems to be caused by having `satip-client` connect to a minisatip instance that uses `satipc` to connect to another instance. When I changed `vtuner.conf` to connect directly to the "backend instance" it works.

It seems like `pids=none` sent to the first minisatip instance gets mangled into something else when it gets passed on to the "backend instance".

Will try to do some more investigating.

**Comment by catalinii** [comment]
Hey,

This I think is a cosmetical error (pids,=...).
I noticed some scanning issues as well and I remember being able to scan.

Would you be able to use openatv 6.4 to see if that works?
Satip-client has a log level settings, can you please upload it here?
To see if this is related to satipclient or enigma2 itself.

**Comment by catalinii** [comment]
@Jalle19 can you try: https://github.com/catalinii/minisatip/commit/e5d6ae1205359765ec1c22d2bf55bd62b71029b0 ?
This works for me.

**Comment by Jalle19** [comment]
@catalinii awesome, it works! Not sure how this change is related to the scanning issue here (Enigma doesn't subscribe to any PIDs if there's no signal detected?), but I'm glad it works.

**Comment by catalinii** [comment]
yeah if the signal is 0, the tuning failed (based on logs) and it does not wait for PAT, PMTs, ... just goes to the next TP.

**Comment by Jalle19** [comment]
Perhaps this should be worked around here in this codebase instead of in minisatip?

**Comment by catalinii** [comment]
Sure, but there are other clients that does this.

The current design (minisatip) is that getting the signal is sync and in case of satipc module, can take longer time to get the actual numbers.
For some old hw reading the signal value can take some time...that's why is async.

**Comment by Jalle19** [comment]
I see :+1:
